name: Pull Request

on:
  pull_request:
  push:
    branches:
      - feature/add-ci

jobs:
  build-beta:
    name: Build Beta
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Compress Build
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: "training-modpack-ui.zip"
          path: "./build"
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Training Modpack UI
          path: training-modpack-ui.zip
